# Use the .NET SDK image to build and run your application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory
WORKDIR /app

# Expose port 80 for the application
EXPOSE 80

# Start a bash shell (for development purposes)
CMD [ "bash" ]
